# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  push_to_quay:
    docker:
      - image: quay.io/sentinelsix/ts-docker-deployment-dev
        environment:
          IMAGE_NAME: quay.io/sentinelsix/streamer      
        auth:
          username: $QUAY_USERNAME
          password: $QUAY_PASSWORD   
    working_directory: ~/repo           
    steps:
      - checkout   
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build & Push Docker image to Quay.io
          command: |
            quay-push.v2.sh            
  deploy_to_development:
    docker:
      - image: quay.io/sentinelsix/ts-docker-deployment-dev
        auth:
          username: $QUAY_USERNAME
          password: $QUAY_PASSWORD
        environment:
          RELEASE_NAME: streamer-dev
          RELEASE_NAMESPACE: default 
          HELM_CHART_NAME: ts-backend-chart
          HELM_VALUES_S3_FOLDER: streamer         
          HELM_VALUES_FILENAME: values.yaml
          HELM_VALUES_BASE_ON: true
          DD_ENVIRONMENT_TAG: development                            
    steps:
      - checkout   
      - run:
          name: Deploying to Development Environment
          command: |
            helm-launcher.v2.sh
  deploy_to_qa:
    docker:
      - image: quay.io/sentinelsix/ts-docker-deployment-dev
        auth:
          username: $QUAY_USERNAME
          password: $QUAY_PASSWORD
        environment:
          RELEASE_NAME: streamer-qa
          RELEASE_NAMESPACE: qa 
          HELM_CHART_NAME: ts-backend-chart
          HELM_VALUES_S3_FOLDER: streamer         
          HELM_VALUES_FILENAME: values.yaml
          HELM_VALUES_BASE_ON: true
          DD_ENVIRONMENT_TAG: qa            
    steps:
      - checkout   
      - run:
          name: Deploying to QA Environment
          command: |
            helm-launcher.v2.sh
  deploy_to_production_primary:
    docker:
      - image: quay.io/sentinelsix/ts-docker-deployment-prod
        auth:
          username: $QUAY_USERNAME
          password: $QUAY_PASSWORD
        environment:
          RELEASE_NAME: streamer-prod
          RELEASE_NAMESPACE: default 
          HELM_CHART_NAME: ts-backend-chart
          HELM_VALUES_S3_FOLDER: streamer         
          HELM_VALUES_FILENAME: values.yaml
          HELM_VALUES_BASE_ON: true
          DD_ENVIRONMENT_TAG: production             
    steps:
      - checkout   
      - run:
          name: Deploying to Production Environment (Primary)
          command: |
            helm-launcher.v2.sh
workflows:
  version: 2
  build_and_deploy:
    jobs: 
      - push_to_quay:
          filters:
            branches:
              only: master              
      - deploy_to_development:
          requires:
            - push_to_quay
          filters:
            branches:
              only: master              
      - approval_to_qa:
          type: approval
          requires:        
            - push_to_quay
            - deploy_to_development             
          filters:
            branches:
              only: master                    
      - deploy_to_qa:
          requires:
            - push_to_quay
            - deploy_to_development
            - approval_to_qa
          filters:
            branches:
              only: master            
      - approval_to_production:
          type: approval
          requires:        
            - push_to_quay
            - deploy_to_development
            - approval_to_qa
            - deploy_to_qa            
          filters:
            branches:
              only: master                         
      - deploy_to_production_primary:
          requires:
            - push_to_quay
            - deploy_to_development
            - approval_to_qa 
            - deploy_to_qa
            - approval_to_production
          filters:
            branches:
              only: master   